backend/.gitignore

feat: 프론트엔트 프로젝트 추가

---

backend/build.gradle
backend/src/main/java/io/pentacore/backend/product/domain/Products.java

feat : Products 엔티티 클래스 작성

---

backend/src/main/java/io/pentacore/backend/product/domain/OrderProduct.java
backend/src/main/java/io/pentacore/backend/product/domain/Products.java

close https://github.com/prgrms-be-devcourse/NBE5-7-1-Team05/issues/4
- 주문-상품 엔티티 OrderProduct 작성
- Products의 Admin 관계 import

feat: OrderProduct 엔티티 작성

---

backend/.gitignore
backend/src/main/java/io/pentacore/backend/admin/dao/AdminRepository.java

close #3 
- admin repository 추가
- .gitignore 파일 수정

feat : admin 레포지토리 추가

---

backend/src/main/java/io/pentacore/backend/product/dao/OrderProductRepository.java
backend/src/main/java/io/pentacore/backend/product/domain/OrderProduct.java

close #15 
- OrderProduct Entity에 대한 JPARepository를 작성했습니다.
- OrderProduct Entity의 Table 명을 명시했습니다.

feat: 주문-상품 레포지토리 추가

---

backend/src/main/java/io/pentacore/backend/global/unit/BaseResponse.java
backend/src/main/java/io/pentacore/backend/product/api/AdminProductController.java
backend/src/main/java/io/pentacore/backend/product/service/ProductService.java

close #12 
- ProductController : Product에 관련한 API 처리를 위한 Controller 입니다.
- ProductService : Product에 관련한 비즈니스 로직 처리를 위한 Service 입니다.
- BaseResponse :  공통적으로 API 응답을 작성하기 위해 작성한 class 입니다.

feat: 관리자 상품 삭제

---

backend/src/main/java/io/pentacore/backend/product/api/AdminProductController.java
backend/src/main/java/io/pentacore/backend/product/api/ProductController.java
backend/src/main/java/io/pentacore/backend/product/app/ProductService.java
backend/src/main/java/io/pentacore/backend/product/service/ProductService.java

Close #23 
##개요
- Product service 에 findall() 추가
- ProductController클래스 getAllProduct추가

feat : Product  search 컨트롤러와 서비스 작성

---

backend/src/main/java/io/pentacore/backend/product/app/ProductService.java
backend/src/main/java/io/pentacore/backend/product/domain/Product.java

feat : Product.java 에 isDeleted 컬럼 추가, softDelete()추가
fix : ProductService.java 에 상품삭제시 softDelet() 함수 사용으로 변경

feat : Product.java 에 isDeleted 컬럼 추가, softDelete()추가

---

backend/build.gradle
backend/src/main/java/io/pentacore/backend/product/api/OrderController.java
backend/src/main/java/io/pentacore/backend/product/app/OrderService.java
backend/src/main/java/io/pentacore/backend/product/app/ProductService.java
backend/src/main/java/io/pentacore/backend/product/dao/OrderRepository.java
backend/src/main/java/io/pentacore/backend/product/domain/Order.java

close #35 
- 주문 취소 구현
- 주문 취소 시 -> 주문 상품으로 cascade

feat : 주문 취소 구현

---

backend/src/main/java/io/pentacore/backend/global/util/EmailValidator.java
backend/src/main/java/io/pentacore/backend/product/api/OrderController.java
backend/src/main/java/io/pentacore/backend/product/api/ProductController.java
backend/src/main/java/io/pentacore/backend/product/app/OrderService.java
backend/src/main/java/io/pentacore/backend/product/dao/OrderRepository.java
backend/src/main/java/io/pentacore/backend/product/domain/Order.java
backend/src/main/java/io/pentacore/backend/product/dto/OrderProductDto.java
backend/src/main/java/io/pentacore/backend/product/dto/OrderResponseDto.java

Close #41 
- 이메일 별 주문 조회 기능 구현
- 이메일 유효성 검사

feat: 주문 조회 기능 추가

---

backend/src/main/java/io/pentacore/backend/product/api/PaymentController.java
backend/src/main/java/io/pentacore/backend/product/app/PaymentService.java
backend/src/main/java/io/pentacore/backend/product/domain/Order.java
backend/src/main/java/io/pentacore/backend/product/domain/OrderProduct.java
backend/src/main/java/io/pentacore/backend/product/domain/Product.java
backend/src/main/java/io/pentacore/backend/product/dto/PaymentRequestDto.java
backend/src/main/java/io/pentacore/backend/product/dto/ProductDto.java

close #36 
- 결제 정보 DTO : PaymentRequestDto, ProductDto
- 결제 로직 처리 : PaymentController, PaymentService
- 결제 시 상품의 재고가 부족할 경우, IllegalArgumentExcption 처리
- 결제 시 상품이 존재하지 않을 경우, NoSuchElementException 처리
- 정상 결제 시 orders 및 order_product 테이블에 정보 입력 및 200 OK 리턴

feat: 결제 정보 등록 (close #36)

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/navigation/NavBar.tsx
frontend/src/contexts/AuthContext.tsx
frontend/src/interface/AuthContextType.tsx
frontend/src/interface/FormErrors.tsx
frontend/src/interface/LoginForm.tsx
frontend/src/interface/SignupForm.tsx
frontend/src/interface/User.tsx
frontend/src/pages/admin/AdminLoginPage.tsx
frontend/src/pages/admin/AdminSignupPage.tsx
frontend/src/pages/shop/ShoppingCartPage.tsx
frontend/src/utils/validation/CheckoutValidation.tsx

Close #45 
- 관리자 로그인 페이지 구현
- 관리자 회원가입 페이지 구현
- 관리자 로그아웃 버튼 생성

feat: 관리자 로그인 회원가입 페이지 구현

---

backend/src/main/java/io/pentacore/backend/BackendApplication.java
backend/src/main/java/io/pentacore/backend/global/scheduler/ProductScheduler.java
backend/src/main/java/io/pentacore/backend/product/app/ProductService.java
backend/src/main/java/io/pentacore/backend/product/dao/ProductRepository.java
backend/src/main/java/io/pentacore/backend/product/domain/Product.java

feat: Product 엔티티에 deletedAt 필드 추가 (soft delete 지원)
feat: ProductService에 deleteExpiredProducts 함수 추가 (만료 상품 삭제)
feat: ProductRepository에 deleteOldSoftDeletedRecords 쿼리 추가 (30일 지난 soft delete 상품 제거)
feat: ProductScheduler 추가 - 매일 자정 soft delete 만료 상품 자동 삭제
chore: @EnableScheduling 어노테이션 추가 (스케줄러 활성화)

feat: 주기적으로 삭제상품 제거

---

backend/src/main/java/io/pentacore/backend/product/api/AdminProductController.java
backend/src/main/java/io/pentacore/backend/product/api/ProductController.java
frontend/src/components/admin/order/AdminOrderManagement.tsx
frontend/src/components/admin/order/OrderDetailModal.tsx
frontend/src/components/admin/order/OrderFilter.tsx
frontend/src/components/admin/product/AdminProductManagement.tsx
frontend/src/components/admin/product/ProductForm.tsx
frontend/src/components/admin/product/ProductTable.tsx
frontend/src/components/admin/product/StockDialog.tsx
frontend/src/components/shop/product/ProductCard.tsx
frontend/src/components/ui/dialog.tsx
frontend/src/components/ui/tabs.tsx
frontend/src/hooks/useProductManagement.ts
frontend/src/interface/Order.tsx
frontend/src/interface/Product.tsx
frontend/src/pages/admin/AdminPage.tsx
frontend/src/pages/shop/ShoppingCartPage.tsx
frontend/src/utils/validation/ProductValidation.tsx

feat: 프론트엔드 상품 CRUD API 연동

---

backend/src/main/java/io/pentacore/backend/product/dto/OrderProductDto.java
backend/src/main/java/io/pentacore/backend/product/dto/OrderResponseDto.java
backend/src/main/java/io/pentacore/backend/product/dto/ProductResponseDto.java

Close #55 
- `ResponseDto` 는 한 번 생성한 후 변경되면 안 되고, 생성자나 빌더로 완성된 이후엔 수정 불가능해야 함. `RequestDto`의 경우 클라이언트의 요청을 받을 때 프레임워크가 빈 객체를 만든 후 setter로 값을 채움.
- Response를 담당하는 `OrderProductDto`, `OrderResponseDto`, `ProductResponseDto` 에 final 추가함.

chore: 응답 DTO final 추가

---

frontend/src/pages/admin/AdminLoginPage.tsx
frontend/src/utils/api/authService.ts
frontend/src/utils/api/axiosConfig.ts

feat: 헤더로 토큰 저장

---

backend/build.gradle
backend/src/main/java/io/pentacore/backend/BackendApplication.java
backend/src/main/java/io/pentacore/backend/admin/api/AdminController.java
backend/src/main/java/io/pentacore/backend/admin/api/TestController.java
backend/src/main/java/io/pentacore/backend/admin/app/AdminContextService.java
backend/src/main/java/io/pentacore/backend/admin/app/AdminService.java
backend/src/main/java/io/pentacore/backend/admin/app/JwtTokenProvider.java
backend/src/main/java/io/pentacore/backend/admin/comfig/JwtAuthFilter.java
backend/src/main/java/io/pentacore/backend/admin/comfig/JwtConfiguration.java
backend/src/main/java/io/pentacore/backend/admin/comfig/SecurityConfig.java
backend/src/main/java/io/pentacore/backend/admin/dao/AdminRepository.java
backend/src/main/java/io/pentacore/backend/admin/dao/BlackListRepository.java
backend/src/main/java/io/pentacore/backend/admin/dao/TokenRepository.java
backend/src/main/java/io/pentacore/backend/admin/domain/Admin.java
backend/src/main/java/io/pentacore/backend/admin/domain/BlackList.java
backend/src/main/java/io/pentacore/backend/admin/domain/RefreshToken.java
backend/src/main/java/io/pentacore/backend/admin/domain/Role.java
backend/src/main/java/io/pentacore/backend/admin/dto/AdminDetails.java
backend/src/main/java/io/pentacore/backend/admin/dto/LoginRequestDto.java
backend/src/main/java/io/pentacore/backend/admin/dto/LoginResponseDto.java
backend/src/main/java/io/pentacore/backend/admin/dto/SingUpRequestDto.java
backend/src/main/java/io/pentacore/backend/admin/dto/TokenBody.java
backend/src/main/java/io/pentacore/backend/admin/dto/TokenDto.java
backend/src/main/java/io/pentacore/backend/product/api/AdminProductController.java
backend/src/main/java/io/pentacore/backend/product/app/ProductService.java
backend/src/main/java/io/pentacore/backend/product/domain/Product.java

feat: 시큐리티 구현

---

backend/src/main/java/io/pentacore/backend/admin/api/AdminController.java
frontend/src/components/auth/PrivateRoute.tsx
frontend/src/contexts/AuthContext.tsx
frontend/src/pages/admin/AdminLoginPage.tsx
frontend/src/pages/shop/ShoppingCartPage.tsx
frontend/src/utils/api/authService.ts
frontend/src/utils/api/axiosConfig.ts

feat: api 연동

---

.github/workflows/gradle.yml
backend/src/main/java/io/pentacore/backend/admin/comfig/SecurityConfig.java

fix: cors 수정

---

backend/src/main/java/io/pentacore/backend/admin/api/AdminController.java
frontend/src/components/auth/PrivateRoute.tsx
frontend/src/contexts/AuthContext.tsx
frontend/src/pages/admin/AdminLoginPage.tsx
frontend/src/pages/shop/ShoppingCartPage.tsx
frontend/src/utils/api/authService.ts
frontend/src/utils/api/axiosConfig.ts

revert "feat: api 연동"

---

backend/src/main/java/io/pentacore/backend/admin/api/AdminController.java
backend/src/main/java/io/pentacore/backend/admin/app/AdminContextService.java
backend/src/main/java/io/pentacore/backend/admin/app/AdminService.java
backend/src/main/java/io/pentacore/backend/admin/dto/AdminDetails.java
backend/src/main/java/io/pentacore/backend/admin/dto/SignUpRequestDto.java
backend/src/main/java/io/pentacore/backend/global/unit/exception/ErrorCode.java
backend/src/main/java/io/pentacore/backend/product/api/AdminProductController.java

close #81 
- AdminContextService 수정
- AdminDetails 에 id 컬럼 추가
- addProduct 부분 수정하고 테스트 완료

feat : 컨트롤러에서 Admin 가져올 수 있도록 구현

---

backend/src/test/java/io/pentacore/backend/OrderCRUDTest.java
backend/src/test/java/io/pentacore/backend/OrderFailureTest.java
backend/src/test/java/io/pentacore/backend/ProductCRUDTest.java
backend/src/test/java/io/pentacore/backend/ProductFailureTest.java
backend/src/test/java/io/pentacore/backend/global/template/AdminAuthRequiredMockMvcTestBase.java
backend/src/test/java/io/pentacore/backend/global/template/MockMvcTestBase.java
backend/src/test/java/io/pentacore/backend/global/template/UserMockMvcTestBase.java
backend/src/test/resources/application.yml

fix #92 
- 테스트에 관리자 인증 필요시 관리자 회원가입 및 로그인 진행
- test application.yml에 security에 필요한 환경변수 등록

fix: 테스트 전 관리자 인증 필요시 인증 진행

---

backend/src/test/java/io/pentacore/backend/OrderFailureTest.java

fix #88 
- 비즈니스 로직 상 문제는 발생하지 않았으며, 테스트 케이스의 url 맵핑이 문제였던 것으로 확인 및 수정

fix: 테스트 케이스의 url 맵핑 오류 해결

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/history/CancelOrderDialog.tsx
frontend/src/components/history/CancelledPurchases.tsx
frontend/src/components/history/PurchaseSummaryCards.tsx
frontend/src/components/history/PurchaseTable.tsx
frontend/src/components/shop/checkout/CheckoutForm.tsx
frontend/src/interface/Order.tsx
frontend/src/interface/PaymentData.tsx
frontend/src/pages/PurchaseHistory.tsx
frontend/src/utils/api/orderService.ts

feat: 주문 관련 API 연동

---

frontend/.gitignore

chore: DS_Store 제거

---

backend/src/main/java/io/pentacore/backend/product/api/AdminOrderController.java
backend/src/main/java/io/pentacore/backend/product/app/OrderService.java

관리자가 모든 주무 검색 기능 추가
adminordersclass 추가 
Oderservic getAllOrders 메서드 추가

feat : 111 adminordersclass 추가 

---

frontend/src/components/admin/order/AdminOrderManagement.tsx
frontend/src/components/admin/order/OrderDetailModal.tsx
frontend/src/components/admin/product/ProductForm.tsx
frontend/src/components/admin/product/ProductTable.tsx
frontend/src/components/history/PurchaseTable.tsx
frontend/src/components/shop/checkout/CheckoutForm.tsx
frontend/src/components/shop/product/ProductCard.tsx
frontend/src/components/ui/badge.tsx
frontend/src/contexts/AuthContext.tsx
frontend/src/hooks/useProductManagement.ts
frontend/src/interface/AuthContextType.tsx
frontend/src/interface/Order.tsx
frontend/src/interface/Product.tsx
frontend/src/pages/PurchaseHistory.tsx
frontend/src/pages/admin/AdminLoginPage.tsx
frontend/src/pages/admin/AdminPage.tsx
frontend/src/pages/shop/ShoppingCartPage.tsx
frontend/src/utils/api/authService.ts
frontend/src/utils/api/axiosConfig.ts
frontend/src/utils/api/orderService.ts
frontend/src/utils/validation/ProductValidation.tsx

close #108 
- 주문 API
- 주문 취소 API
- 이메일별 주문 조회 API
- 관리자 전체 주문 조회 API
- 상품 추가 API
- 상품 삭제 API
- 상품 수정 API
- 상품 조회 API

feat: 모든 API 연동

---

frontend/src/components/history/EmailDialog.tsx
frontend/src/components/ui/card.tsx
frontend/src/pages/PurchaseHistory.tsx
frontend/src/pages/admin/AdminPage.tsx
frontend/src/pages/shop/ShoppingCartPage.tsx

close #119 
구매 내역 페이지에서 현재 이메일 표시 및 이메일 변경 버튼 위치 조정

design: ui 개선

---

frontend/src/App.tsx
frontend/src/components/admin/order/AdminOrderManagement.tsx
frontend/src/components/history/PurchaseFilters.tsx
frontend/src/components/history/PurchaseSummaryCards.tsx
frontend/src/components/layout/Footer.tsx
frontend/src/pages/admin/AdminPage.tsx
frontend/src/pages/shop/ShoppingCartPage.tsx
frontend/src/pages/user/PurchaseHistory.tsx
frontend/src/utils/date/dateUtils.ts

close #121 
주문 조회 시 한국 시간으로 조회

fix: 주문 조회 시 한국 시간으로 조회

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/admin/AdminPage.tsx
frontend/src/pages/user/PurchaseHistory.tsx
frontend/src/utils/api/axiosConfig.ts

close #125 
- 토큰 만료 10초 전에 요청 보내게 구현
- 401 또는 403일 때도 요청 전송

fix: 토큰 재발급 무한 요청 해결
